nguage: node_js
node_js:
- "0.11"
- "0.10"
before_script:
- gem install sass
- npm install
script:
- gulp bower
- gulp
deploy:
  provider: s3
  access_key_id: AKIAIJGTHZSMAJWMNFFQ
  secret_access_key:
    secure: AXp3K81vNgsD4hz14cMVTkoomZpOPPyw3pNhVgLWRsRQhomlrISAwm2udl9fYHJqwvZ1yYJLiZYnb/vXukQ7opqtc9bDQLCxh7SzWZr/mewQqIavMx2Q61n5WhFgh3KVxME6kJvL77ZCWYMVDb30NqSIgWBTq/Lv3VGF/xGNhlQfaXT6XDFcX5Oefz0D2M+Rh2d5VG5NkSEnTZQMkByr3OOExum47xiEbG7s8ka4G82hhIXnUjS4CULFznEc/jYjIULC3dU3q5Wjzw9tpGeMPBYU+jkGB+D99+Cr4Qdl8jps8opqX4SPijSATtEpet2ZbODtcXrAdyS5utDnk3I5WcJCIOGNa4EXbB7MO4pPBbXgJQ+hSdy++0rVJEplNKN2xp4xQoJ6s+BgHzsswCtFerIuZJ0Guud8Mb4F/cnl8/ecV6SDYSP4IfCN13jcLQ2umBDD28S7VcyiABZX2X4imQCzFbuYxFttLgVLcaO5Ui3zr/9SWzTawvGirQ0zQYzd1s9BRz03Ku0Of7+gsZUAuqikz/3s7dh9cz9nCnHEs2s/yzzZsOWBSJqvCdS8UxwcpEtX8wVV/sLyBGPYiJmxucPkELxVSNB5rozl0NtK+GzPt7mTEhRige6DElgVVANvZgC/lyuMfJb9WPRhdJQ8FWCRgV3JwAPR+oJ79A6hFOQ=
  bucket: dvowebsite
  skip_cleanup: true
  local-dir: web
  acl: public_read
  on:
    repo: dvomedia/travis-test
